version: '3'

services:
  api:
    build: api
    image: pokemon-search-engine
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/api
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"

  client:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  node-modules: